name: phone_auth
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.3.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.1
  get: 4.6.5
  pin_code_fields: ^7.4.0
  result_type: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
